# nixpacks.toml

[phases.setup]
nixPkgs = [
    "nodejs",
    "fontconfig",
    "jetbrains-mono",    
    "noto-fonts-cjk",    # <--- WAJIB: Untuk huruf Jepang/Cina/Korea
    "noto-fonts-emoji"   # <--- WAJIB: Untuk render Emoji
]

[start]
cmd = "node src/index.js"
