# nixpacks.toml

[phases.setup]
nixPkgs = [
    "nodejs",
    "fontconfig",
    "jetbrains-mono",
    "noto-fonts-cjk-sans",   # <--- UPDATED: Changed from noto-fonts-cjk
    "noto-fonts-emoji"
]

[start]
cmd = "node src/index.js"